language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  pip: true

before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run mypy -p pta
  - poetry run flake8 pta
  - poetry run pytest
after_success:
  - poetry run codecov
